name: hopefund-banking

services:
  # Backend API
  - name: api
    github:
      repo: kouadiojose/hopefund
      branch: claude/hopefund-banking-app-M021u
      deploy_on_push: true
    source_dir: apps/api
    build_command: rm -f package-lock.json && npm install && npx prisma generate && npm run build
    run_command: node dist/index.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
    routes:
      - path: /api

  # Frontend Web App (Static Site)
  - name: web
    github:
      repo: kouadiojose/hopefund
      branch: claude/hopefund-banking-app-M021u
      deploy_on_push: true
    source_dir: apps/web
    build_command: npm install && npm run build
    environment_slug: html
    routes:
      - path: /
